# Enable unstable web-sys APIs (WebSerial, WebUSB) for ALL crates when targeting wasm32
# See: https://wasm-bindgen.github.io/wasm-bindgen/web-sys/unstable-apis.html
[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis"]
